// Compiled-in list of Instagram (ig_icon_/bcn_) asset names for the icon
// browser. Body generated by scripts/gen_ig_icons.py on every build.
#import <Foundation/Foundation.h>

NSArray<NSString *> *RYGGeneratedIGIconNames(void);
