#import "RYGDeveloperTopicViewController.h"
#import "RYGRuntimeBrowserEngine.h"
#import "RYGEasyGatingRuntime.h"
#import "../Features/ExpFlags/RYGMobileConfig.h"
#import "../Features/ExpFlags/RYGMobileConfigJSONIO.h"
#import "../UI/RYGLiquidGlass.h"
#import "../UI/RYGPopupChrome.h"
#import "../Utils.h"
#import <objc/runtime.h>
#import <objc/message.h>
#include <string.h>

static NSString *const kRYGDevMethodModes=@"ryg_dev_exact_method_modes_v4";
static NSString *const kRYGInternalMenuPref=@"ryg_dev_internal_menu_enabled";
static NSString *const kRYGDogfoodModePref=@"ryg_dev_dogfood_mode_enabled";
static NSString *const kRYGDogfoodOwnedMCPref=@"ryg_dev_dogfood_owned_mc_by_name_v1";
static NSString *const kRYGThrowbackPref=@"ryg_dev_throwback_chrome_enabled";
static NSString *const kRYGNavGlassPref=@"ryg_dev_navigation_glass_enabled";
static NSString *const kRYGSwizzleGlassPref=@"ryg_dev_swizzle_glass_enabled";
static const void *kRYGRowKey=&kRYGRowKey;

static IMP gBugMenuOriginal;
static IMP gDogfoodSettingsInitOriginal;
static id gDogfoodConfig;
static id gDogfoodSession;

static const char *RYGUnqual(const char*t){while(t&&*t&&strchr("rnNoORV",*t))t++;return t;}
static BOOL RYGTypeBool(const char*t){t=RYGUnqual(t);return t&&strchr("BcC",*t)!=NULL;}
static BOOL RYGTypeObject(const char*t){t=RYGUnqual(t);return t&&*t=='@';}
static BOOL RYGTypeInt64(const char*t){t=RYGUnqual(t);return t&&(*t=='q'||*t=='Q');}
static BOOL RYGReturns(Method m,char expected){if(!m)return NO;char t[96]={0};method_getReturnType(m,t,sizeof(t));const char*u=RYGUnqual(t);if(!u)return NO;if(expected=='B')return RYGTypeBool(u);return *u==expected;}
static BOOL RYGArg(Method m,unsigned int index,char expected){if(!m||index>=method_getNumberOfArguments(m))return NO;char t[96]={0};method_getArgumentType(m,index,t,sizeof(t));if(expected=='@')return RYGTypeObject(t);if(expected=='B')return RYGTypeBool(t);if(expected=='Q')return RYGTypeInt64(t);return NO;}
static RYGRuntimeArgumentKind RYGKind(Method m){if(!m||!RYGReturns(m,'B'))return(RYGRuntimeArgumentKind)-1;unsigned int c=method_getNumberOfArguments(m);if(c==2)return RYGRuntimeArgumentNone;if(c!=3)return(RYGRuntimeArgumentKind)-1;char t[96]={0};method_getArgumentType(m,2,t,sizeof(t));if(RYGTypeObject(t))return RYGRuntimeArgumentObject;if(RYGTypeInt64(t))return RYGRuntimeArgumentInteger;return(RYGRuntimeArgumentKind)-1;}

static RYGRuntimeBoolMethod *RYGExact(NSString*className,NSString*selectorName,BOOL classMethod){Class cls=className.length?objc_lookUpClass(className.UTF8String):Nil;if(!cls||!selectorName.length)return nil;Class owner=classMethod?object_getClass(cls):cls;Method m=owner?class_getInstanceMethod(owner,NSSelectorFromString(selectorName)):NULL;RYGRuntimeArgumentKind kind=RYGKind(m);if(kind<RYGRuntimeArgumentNone||kind>RYGRuntimeArgumentInteger)return nil;RYGRuntimeBoolMethod*r=[RYGRuntimeBoolMethod new];r.className=className;r.selectorName=selectorName;r.classMethod=classMethod;r.argumentKind=kind;const char*types=method_getTypeEncoding(m);r.typeEncoding=types?[NSString stringWithUTF8String:types]:@"";const char*image=class_getImageName(cls);r.imagePath=image?[NSString stringWithUTF8String:image]:@"";return r;}
static NSString *RYGModeIdentity(RYGRuntimeBoolMethod*m){return[NSString stringWithFormat:@"%@|%@|%@",m.classMethod?@"+":@"-",m.className?:@"",m.selectorName?:@""];}
static BOOL RYGParseModeIdentity(NSString*k,BOOL*classMethod,NSString**className,NSString**selectorName){NSArray*p=[k componentsSeparatedByString:@"|"];if(p.count!=3)return NO;if(classMethod)*classMethod=[p[0] isEqualToString:@"+"];if(className)*className=p[1];if(selectorName)*selectorName=p[2];return YES;}
static NSMutableDictionary *RYGModeStore(void){id raw=[NSUserDefaults.standardUserDefaults dictionaryForKey:kRYGDevMethodModes];return[raw isKindOfClass:NSDictionary.class]?[raw mutableCopy]:[NSMutableDictionary dictionary];}
static NSInteger RYGStoredMode(RYGRuntimeBoolMethod*m){NSNumber*v=RYGModeStore()[RYGModeIdentity(m)];return[v isKindOfClass:NSNumber.class]?v.integerValue:-1;}
static void RYGSetStoredMode(RYGRuntimeBoolMethod*m,NSInteger mode){if(!m)return;NSMutableDictionary*d=RYGModeStore();NSString*k=RYGModeIdentity(m);if(mode<0)[d removeObjectForKey:k];else d[k]=@(mode);[NSUserDefaults.standardUserDefaults setObject:d.copy forKey:kRYGDevMethodModes];[RYGRuntimeBrowserEngine setOverride:mode<0?nil:@(mode!=0) forMethod:m];}
static void RYGReapplyStoredMethods(void){NSDictionary*d=[NSUserDefaults.standardUserDefaults dictionaryForKey:kRYGDevMethodModes];[d enumerateKeysAndObjectsUsingBlock:^(NSString*k,NSNumber*v,BOOL*stop){(void)stop;BOOL cm=NO;NSString*c=nil,*s=nil;if(!RYGParseModeIdentity(k,&cm,&c,&s)||![v isKindOfClass:NSNumber.class])return;RYGRuntimeBoolMethod*m=RYGExact(c,s,cm);if(m)[RYGRuntimeBrowserEngine setOverride:@(v.boolValue) forMethod:m];}];}

static NSArray<RYGRuntimeBoolMethod*> *RYGStrictMethodsForOwner(NSString*className,BOOL classMethods){Class cls=objc_lookUpClass(className.UTF8String),owner=cls?(classMethods?object_getClass(cls):cls):Nil;if(!owner)return@[];unsigned int count=0;Method*methods=class_copyMethodList(owner,&count);NSMutableArray*out=[NSMutableArray array];for(unsigned int i=0;methods&&i<count;i++){SEL sel=method_getName(methods[i]);if(!sel)continue;RYGRuntimeBoolMethod*r=RYGExact(className,NSStringFromSelector(sel),classMethods);if(r&&! [RYGRuntimeBrowserEngine isStructuralNoiseSelectorName:r.selectorName])[out addObject:r];}if(methods)free(methods);[out sortUsingComparator:^NSComparisonResult(RYGRuntimeBoolMethod*a,RYGRuntimeBoolMethod*b){return[a.selectorName localizedCaseInsensitiveCompare:b.selectorName];}];return out.copy;}

static NSString *RYGSurfaceTitle(RYGDeveloperRuntimeSurface s){switch(s){case RYGDeveloperRuntimeSurfacePrism:return@"Prism / Redesign";case RYGDeveloperRuntimeSurfaceLiquidGlass:return@"Liquid Glass";case RYGDeveloperRuntimeSurfaceStories:return@"Stories / Story Tray";case RYGDeveloperRuntimeSurfaceConsumerSubs:return@"SubsConsumer / IGPlus / Aura";case RYGDeveloperRuntimeSurfaceInternalOnly:case RYGDeveloperRuntimeSurfaceBugReport:case RYGDeveloperRuntimeSurfaceSettingsRows:return@"IG-only / Internal-only";case RYGDeveloperRuntimeSurfaceDirectDogfood:return@"Dogfooding";}return@"Developer";}
static NSArray<RYGRuntimeBoolMethod*> *RYGSurfaceMethods(RYGDeveloperRuntimeSurface s){NSMutableArray*out=[NSMutableArray array];void(^add)(NSString*,NSString*,BOOL)=^(NSString*c,NSString*sel,BOOL cm){RYGRuntimeBoolMethod*r=RYGExact(c,sel,cm);if(r)[out addObject:r];};switch(s){case RYGDeveloperRuntimeSurfacePrism:add(@"IGFeedItemAdsFeedbackInterfaceCellParams",@"isPrismEnabled",NO);add(@"IGTableViewCell",@"isListRedesignOn",NO);break;case RYGDeveloperRuntimeSurfaceStories:add(@"_TtC27IGPersistentStoryTrayGating38IGPersistentStoryTrayGatingStaticFuncs",@"isTrayAttachedToHeaderEnabled:",YES);add(@"_TtC38IGStoryViewerRedesignExperimentHelpers38IGStoryViewerRedesignExperimentHelpers",@"isStoryViewerCardAnimationEnabledWithLauncherSet:",YES);break;case RYGDeveloperRuntimeSurfaceConsumerSubs:[out addObjectsFromArray:RYGStrictMethodsForOwner(@"_TtC21IGConsumerSubsService21IGConsumerSubsService",NO)];add(@"_TtC22IGProfileGatingService22IGProfileGatingService",@"isAuraQuietPostingEnabledWithConsumerSubsService:",YES);break;case RYGDeveloperRuntimeSurfaceLiquidGlass:[out addObjectsFromArray:RYGStrictMethodsForOwner(@"_TtC15IGThrowbackFeed21IGThrowbackFeedHelper",YES)];break;default:break;}return out.copy;}

#pragma mark - exact internal/dogfood native hooks via method_setImplementation

typedef id(*RYGBugMenuFn)(id,SEL,id,id,id,id,id,id,long long,long long,BOOL,BOOL,BOOL,BOOL,long long);
static BOOL RYGBugSignature(Method m){if(!m||method_getNumberOfArguments(m)!=15||!RYGReturns(m,'@'))return NO;for(unsigned int i=2;i<=7;i++)if(!RYGArg(m,i,'@'))return NO;if(!RYGArg(m,8,'Q')||!RYGArg(m,9,'Q'))return NO;for(unsigned int i=10;i<=13;i++)if(!RYGArg(m,i,'B'))return NO;return RYGArg(m,14,'Q');}
static id RYGBugReplacement(id self,SEL cmd,id device,id session,id reliability,id nav,id endpoint,id entry,long long style,long long availability,BOOL showInternal,BOOL showLoggedOut,BOOL showShake,BOOL showDogfood,long long variant){BOOL dog=[NSUserDefaults.standardUserDefaults boolForKey:kRYGDogfoodModePref],internal=dog||[NSUserDefaults.standardUserDefaults boolForKey:kRYGInternalMenuPref];RYGBugMenuFn orig=(RYGBugMenuFn)gBugMenuOriginal;return orig?orig(self,cmd,device,session,reliability,nav,endpoint,entry,style,availability,internal?YES:showInternal,internal?YES:showLoggedOut,showShake,dog?YES:showDogfood,variant):nil;}
static BOOL RYGInstallInternalMenuHook(void){if(gBugMenuOriginal)return YES;Class cls=objc_lookUpClass("_TtC17IGBugReporterMenu29IGBugReportMenuViewController");SEL sel=NSSelectorFromString(@"initWithDeviceSession:userSession:reliabilityLogging:navChain:endpoint:entryPoint:style:internalSettingsAvailabilityStatus:showInternalSettings:showLoggedOutInternalSettings:showShakeToReportPreferenceToggle:showDogfoodingAssistant:maisaUXVariantRawValue:");Method m=cls?class_getInstanceMethod(cls,sel):NULL;if(!RYGBugSignature(m))return NO;gBugMenuOriginal=method_setImplementation(m,(IMP)RYGBugReplacement);return gBugMenuOriginal!=NULL;}

typedef id(*RYGDogInitFn)(id,SEL,id,id);
static id RYGDogInitReplacement(id self,SEL cmd,id config,id session){if(config)gDogfoodConfig=config;if(session)gDogfoodSession=session;RYGDogInitFn orig=(RYGDogInitFn)gDogfoodSettingsInitOriginal;return orig?orig(self,cmd,config,session):nil;}
static BOOL RYGInstallDogfoodCapture(void){if(gDogfoodSettingsInitOriginal)return YES;Class cls=objc_lookUpClass("_TtC20IGDogfoodingSettings34IGDogfoodingSettingsViewController");SEL sel=NSSelectorFromString(@"initWithConfig:userSession:");Method m=cls?class_getInstanceMethod(cls,sel):NULL;if(!m||method_getNumberOfArguments(m)!=4||!RYGReturns(m,'@')||!RYGArg(m,2,'@')||!RYGArg(m,3,'@'))return NO;gDogfoodSettingsInitOriginal=method_setImplementation(m,(IMP)RYGDogInitReplacement);return gDogfoodSettingsInitOriginal!=NULL;}
static UIViewController *RYGTop(void){UIWindow*key=nil;for(UIScene*s in UIApplication.sharedApplication.connectedScenes){if(![s isKindOfClass:UIWindowScene.class]||s.activationState!=UISceneActivationStateForegroundActive)continue;for(UIWindow*w in((UIWindowScene*)s).windows)if(w.isKeyWindow){key=w;break;}if(key)break;}UIViewController*top=key.rootViewController;for(;;){UIViewController*n=nil;if(top.presentedViewController&&!top.presentedViewController.isBeingDismissed)n=top.presentedViewController;else if([top isKindOfClass:UINavigationController.class])n=((UINavigationController*)top).visibleViewController;else if([top isKindOfClass:UITabBarController.class])n=((UITabBarController*)top).selectedViewController;if(!n||n==top)break;top=n;}return top;}
static BOOL RYGOpenDogfood(void){RYGInstallDogfoodCapture();if(!gDogfoodConfig||!gDogfoodSession)return NO;Class cls=objc_lookUpClass("_TtC20IGDogfoodingSettings20IGDogfoodingSettings");SEL sel=NSSelectorFromString(@"openWithConfig:onViewController:userSession:");Method m=cls?class_getClassMethod(cls,sel):NULL;UIViewController*top=RYGTop();if(!top||!m||method_getNumberOfArguments(m)!=5||!RYGReturns(m,'v')||!RYGArg(m,2,'@')||!RYGArg(m,3,'@')||!RYGArg(m,4,'@'))return NO;((void(*)(id,SEL,id,id,id))objc_msgSend)((id)cls,sel,gDogfoodConfig,top,gDogfoodSession);return YES;}

#pragma mark - Native bool helpers
static id RYGShared(NSString*className){Class cls=objc_lookUpClass(className.UTF8String);SEL sel=NSSelectorFromString(@"shared");Method m=cls?class_getClassMethod(cls,sel):NULL;if(!m||method_getNumberOfArguments(m)!=2||!RYGReturns(m,'@'))return nil;return((id(*)(id,SEL))objc_msgSend)((id)cls,sel);}
static NSNumber *RYGHelperValue(NSString*c){id h=RYGShared(c);SEL s=NSSelectorFromString(@"isEnabled");Method m=h?class_getInstanceMethod([h class],s):NULL;if(!m||method_getNumberOfArguments(m)!=2||!RYGReturns(m,'B'))return nil;return@(((BOOL(*)(id,SEL))objc_msgSend)(h,s));}
static BOOL RYGSetHelper(NSString*c,NSString*selector,BOOL value){id h=RYGShared(c);SEL s=NSSelectorFromString(selector);Method m=h?class_getInstanceMethod([h class],s):NULL;if(!m||method_getNumberOfArguments(m)!=3||!RYGReturns(m,'v')||!RYGArg(m,2,'B'))return NO;((void(*)(id,SEL,BOOL))objc_msgSend)(h,s,value);return YES;}

#pragma mark - name-resolved MobileConfig dogfood targets; no numeric IDs
static NSString *RYGNorm(NSString*s){if(!s.length)return@"";NSString*l=s.lowercaseString;NSMutableString*o=[NSMutableString string];for(NSUInteger i=0;i<l.length;i++){unichar c=[l characterAtIndex:i];if((c>='a'&&c<='z')||(c>='0'&&c<='9'))[o appendFormat:@"%C",c];}return o;}
static BOOL RYGDogTarget(RYGMCConfig*c,RYGMCParam*p){NSString*cn=RYGNorm(c.name),*pn=RYGNorm(p.name);if([cn containsString:@"igisemployee"]&&[pn containsString:@"employee"])return YES;if([cn containsString:@"igdogfoodingassistant"]&&[pn containsString:@"showinbugreportmenu"])return YES;if([cn containsString:@"igdogfoodingfirstclient"]&&([pn isEqualToString:@"isenabled"]||[pn containsString:@"enabled"]))return YES;return NO;}
static NSString *RYGMCIdentity(RYGMCParam*p){return[NSString stringWithFormat:@"%u:%u",p.configNumber,p.paramIndex];}
static NSUInteger RYGApplyDogfoodNamedMC(BOOL enabled){RYGMobileConfig*mc=RYGMobileConfig.shared;[mc prepare];NSMutableDictionary*owned=[[[NSUserDefaults standardUserDefaults]dictionaryForKey:kRYGDogfoodOwnedMCPref] mutableCopy]?:[NSMutableDictionary dictionary];NSUInteger changed=0;for(RYGMCConfig*c in mc.allConfigs){for(RYGMCParam*p in c.params){if(!p.isRuntimeBacked||p.type!=RYGMCTypeBool||!RYGDogTarget(c,p))continue;NSString*k=RYGMCIdentity(p);if(enabled){if(!owned[k]){id old=[mc overrideValueFor:p];owned[k]=@{@"had":@([mc overrideStateFor:p]==RYGMCOverrideSet),@"value":old?:@NO};}if([mc setOverride:@YES for:p])changed++;}else{NSDictionary*state=[owned[k] isKindOfClass:NSDictionary.class]?owned[k]:nil;if(!state)continue;if([state[@"had"] boolValue])[mc setOverride:state[@"value"]?:@NO for:p];else[mc clearOverrideFor:p];[owned removeObjectForKey:k];changed++;}}}if(owned.count)[NSUserDefaults.standardUserDefaults setObject:owned.copy forKey:kRYGDogfoodOwnedMCPref];else[NSUserDefaults.standardUserDefaults removeObjectForKey:kRYGDogfoodOwnedMCPref];[mc ryg_syncPersistedJSONToNativeDataDirectory];return changed;}

static BOOL RYGOpenStoryDebug(void){RYGRuntimeBoolMethod*gate=RYGExact(@"_TtC27IGPersistentStoryTrayGating38IGPersistentStoryTrayGatingStaticFuncs",@"isTrayAttachedToHeaderEnabled:",YES);if(!gate)return NO;NSNumber*current=gate.overrideValue?:gate.liveValue;if(!current)current=@NO;Class cls=objc_lookUpClass("_TtC25IGOverlayStoriesTrayDebug39IGOverlayStoriesTrayDebugViewController");SEL sel=NSSelectorFromString(@"presentFrom:currentlyEnabled:onApplyAndRestart:");Method m=cls?class_getClassMethod(cls,sel):NULL;UIViewController*top=RYGTop();if(!top||!m||method_getNumberOfArguments(m)!=5||!RYGReturns(m,'v')||!RYGArg(m,2,'@')||!RYGArg(m,3,'B')||!RYGArg(m,4,'@'))return NO;void(^completion)(BOOL)=^(BOOL enabled){RYGSetStoredMode(gate,enabled?1:0);};((void(*)(id,SEL,id,BOOL,id))objc_msgSend)((id)cls,sel,top,current.boolValue,completion);return YES;}

@interface RYGDeveloperTopicViewController()
@property(nonatomic,assign)RYGDeveloperRuntimeSurface surface;@property(nonatomic,copy)NSArray<RYGRuntimeBoolMethod*>*methods;@property(nonatomic,copy)NSArray<NSDictionary*>*controls;
@end
@implementation RYGDeveloperTopicViewController
-(instancetype)initWithSurface:(RYGDeveloperRuntimeSurface)s{if((self=[super initWithStyle:UITableViewStyleInsetGrouped])){_surface=s;}return self;}
+(void)activatePersistedNativeFeatures{RYGReapplyStoredMethods();NSUserDefaults*d=NSUserDefaults.standardUserDefaults;BOOL dog=[d boolForKey:kRYGDogfoodModePref],internal=dog||[d boolForKey:kRYGInternalMenuPref];if(internal)RYGInstallInternalMenuHook();if(dog){RYGInstallDogfoodCapture();[RYGEasyGatingRuntime.shared installIfNeeded];RYGApplyDogfoodNamedMC(YES);}if([d objectForKey:kRYGThrowbackPref])RYGSetHelper(@"_TtC29IGLiquidGlassExperimentHelper33IGThrowbackChromeExperimentHelper",@"overrideIsEnabled:",[d boolForKey:kRYGThrowbackPref]);if([d objectForKey:kRYGNavGlassPref])RYGSetHelper(@"_TtC29IGLiquidGlassExperimentHelper39IGLiquidGlassNavigationExperimentHelper",@"overrideIsEnabled:",[d boolForKey:kRYGNavGlassPref]);if([d objectForKey:kRYGSwizzleGlassPref])RYGSetHelper(@"_TtC20IGLiquidGlassSwizzle26IGLiquidGlassSwizzleToggle",@"setIsEnabled:",[d boolForKey:kRYGSwizzleGlassPref]);}
-(void)viewDidLoad{[super viewDidLoad];self.title=RYGSurfaceTitle(self.surface);self.navigationItem.titleView=RYGLiquidGlassNavigationTitleView(self.title);self.view.backgroundColor=[RYGPopupChrome backgroundColor];self.tableView.backgroundColor=[RYGPopupChrome backgroundColor];self.tableView.rowHeight=UITableViewAutomaticDimension;self.tableView.estimatedRowHeight=56;self.methods=RYGSurfaceMethods(self.surface);[self buildControls];RYGLiquidGlassApplyToViewController(self);}
-(void)buildControls{NSMutableArray*r=[NSMutableArray array];switch(self.surface){case RYGDeveloperRuntimeSurfaceLiquidGlass:[r addObjectsFromArray:@[@{@"kind":@"helper",@"title":@"Throwback Chrome",@"class":@"_TtC29IGLiquidGlassExperimentHelper33IGThrowbackChromeExperimentHelper",@"setter":@"overrideIsEnabled:",@"pref":kRYGThrowbackPref},@{@"kind":@"helper",@"title":@"Navigation Liquid Glass",@"class":@"_TtC29IGLiquidGlassExperimentHelper39IGLiquidGlassNavigationExperimentHelper",@"setter":@"overrideIsEnabled:",@"pref":kRYGNavGlassPref},@{@"kind":@"helper",@"title":@"Liquid Glass Swizzle",@"class":@"_TtC20IGLiquidGlassSwizzle26IGLiquidGlassSwizzleToggle",@"setter":@"setIsEnabled:",@"pref":kRYGSwizzleGlassPref}]];break;case RYGDeveloperRuntimeSurfaceStories:[r addObject:@{@"kind":@"story",@"title":@"Open native Story Tray Debug"}];break;case RYGDeveloperRuntimeSurfaceInternalOnly:case RYGDeveloperRuntimeSurfaceBugReport:case RYGDeveloperRuntimeSurfaceSettingsRows:[r addObject:@{@"kind":@"internal",@"title":@"Expose Internal Settings"}];break;case RYGDeveloperRuntimeSurfaceDirectDogfood:[r addObjectsFromArray:@[@{@"kind":@"dogfood",@"title":@"Global Dogfooding Mode"},@{@"kind":@"dogopen",@"title":@"Open native Dogfooding Settings"},@{@"kind":@"easy",@"title":@"Install EasyGating observer"}]];break;default:break;}self.controls=r.copy;}
-(NSInteger)numberOfSectionsInTableView:(UITableView*)tableView{(void)tableView;return(self.controls.count?1:0)+(self.methods.count?1:0);}
-(NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section{(void)tableView;if(self.controls.count&&section==0)return self.controls.count;return self.methods.count;}
-(NSString*)tableView:(UITableView*)tableView titleForHeaderInSection:(NSInteger)section{(void)tableView;if(self.controls.count&&section==0)return@"Native controls";return self.methods.count?@"ABI-validated gates":nil;}
-(RYGRuntimeBoolMethod*)methodAt:(NSIndexPath*)ip{NSInteger s=ip.section-(self.controls.count?1:0);if(s!=0||ip.row>=self.methods.count)return nil;return self.methods[ip.row];}
-(UIButton*)modeButton:(RYGRuntimeBoolMethod*)m{NSInteger mode=RYGStoredMode(m);NSString*title=mode<0?@"Native":(mode?@"Forced On":@"Forced Off");__weak typeof(self)w=self;UIAction*(^make)(NSString*,NSInteger)=^UIAction*(NSString*t,NSInteger v){UIAction*a=[UIAction actionWithTitle:t image:nil identifier:nil handler:^(__unused UIAction*x){RYGSetStoredMode(m,v);[w.tableView reloadData];}];a.state=mode==v?UIMenuElementStateOn:UIMenuElementStateOff;return a;};UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem];b.menu=[UIMenu menuWithTitle:m.selectorName image:nil identifier:nil options:UIMenuOptionsSingleSelection children:@[make(@"Native",-1),make(@"Force On",1),make(@"Force Off",0)]];b.showsMenuAsPrimaryAction=YES;RYGLiquidGlassConfigureButton(b,NO);UIButtonConfiguration*c=b.configuration;if(c){c.title=title;b.configuration=c;}else[b setTitle:title forState:UIControlStateNormal];return b;}
-(void)toggleChanged:(UISwitch*)toggle{NSDictionary*row=objc_getAssociatedObject(toggle,kRYGRowKey);NSString*kind=row[@"kind"];BOOL requested=toggle.isOn;if([kind isEqualToString:@"internal"]){[NSUserDefaults.standardUserDefaults setBool:requested forKey:kRYGInternalMenuPref];if(requested&&!RYGInstallInternalMenuHook())toggle.on=NO;}else if([kind isEqualToString:@"dogfood"]){[NSUserDefaults.standardUserDefaults setBool:requested forKey:kRYGDogfoodModePref];if(requested){RYGInstallInternalMenuHook();RYGInstallDogfoodCapture();[RYGEasyGatingRuntime.shared installIfNeeded];RYGApplyDogfoodNamedMC(YES);}else RYGApplyDogfoodNamedMC(NO);}else if([kind isEqualToString:@"helper"]){NSString*c=row[@"class"],*setter=row[@"setter"],*pref=row[@"pref"];if(!RYGSetHelper(c,setter,requested)){toggle.on=!requested;return;}[NSUserDefaults.standardUserDefaults setBool:requested forKey:pref];}}
-(UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)ip{UITableViewCell*cell=[tableView dequeueReusableCellWithIdentifier:@"RYGDevExact"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"RYGDevExact"];cell.accessoryView=nil;cell.accessoryType=UITableViewCellAccessoryNone;cell.selectionStyle=UITableViewCellSelectionStyleNone;if(self.controls.count&&ip.section==0){NSDictionary*r=self.controls[ip.row];NSString*k=r[@"kind"];cell.textLabel.text=r[@"title"];if([k isEqualToString:@"story"]||[k isEqualToString:@"dogopen"]||[k isEqualToString:@"easy"]){cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;cell.selectionStyle=UITableViewCellSelectionStyleDefault;}else{UISwitch*t=[UISwitch new];if([k isEqualToString:@"internal"])t.on=[NSUserDefaults.standardUserDefaults boolForKey:kRYGInternalMenuPref];else if([k isEqualToString:@"dogfood"])t.on=[NSUserDefaults.standardUserDefaults boolForKey:kRYGDogfoodModePref];else if([k isEqualToString:@"helper"]){NSString*pref=r[@"pref"];id saved=[NSUserDefaults.standardUserDefaults objectForKey:pref];NSNumber*native=RYGHelperValue(r[@"class"]);t.on=saved?[saved boolValue]:native.boolValue;}objc_setAssociatedObject(t,kRYGRowKey,r,OBJC_ASSOCIATION_RETAIN_NONATOMIC);[t addTarget:self action:@selector(toggleChanged:) forControlEvents:UIControlEventValueChanged];cell.accessoryView=t;}return cell;}RYGRuntimeBoolMethod*m=[self methodAt:ip];cell.textLabel.text=[NSString stringWithFormat:@"%@ %@",m.classMethod?@"+":@"−",m.selectorName?:@""];cell.textLabel.font=[UIFont monospacedSystemFontOfSize:12.5 weight:UIFontWeightMedium];cell.textLabel.numberOfLines=2;cell.detailTextLabel.text=[NSString stringWithFormat:@"%@\n%@",m.className?:@"",m.typeEncoding?:@""];cell.detailTextLabel.numberOfLines=2;cell.detailTextLabel.textColor=UIColor.secondaryLabelColor;cell.accessoryView=[self modeButton:m];return cell;}
-(void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)ip{[tableView deselectRowAtIndexPath:ip animated:YES];if(!(self.controls.count&&ip.section==0))return;NSString*k=self.controls[ip.row][@"kind"];if([k isEqualToString:@"story"]){if(!RYGOpenStoryDebug())[RYGUtils showErrorHUDWithDescription:@"Native Story Tray presenter/gate ABI is not available in this build."];}else if([k isEqualToString:@"dogopen"]){if(!RYGOpenDogfood())[RYGUtils showErrorHUDWithDescription:@"No real IGDogfoodingSettingsConfig has been captured yet. Open the native Dogfooding Assistant once, then retry."];}else if([k isEqualToString:@"easy"]){[RYGEasyGatingRuntime.shared installIfNeeded];[RYGUtils showToastForDuration:1.0 title:@"EasyGating observer installed" subtitle:nil];}}
@end

__attribute__((constructor(210)))static void RYGDeveloperPersistedBootstrap(void){@autoreleasepool{NSUserDefaults*d=NSUserDefaults.standardUserDefaults;BOOL has=[d dictionaryForKey:kRYGDevMethodModes].count||[d boolForKey:kRYGInternalMenuPref]||[d boolForKey:kRYGDogfoodModePref]||[d objectForKey:kRYGThrowbackPref]||[d objectForKey:kRYGNavGlassPref]||[d objectForKey:kRYGSwizzleGlassPref];if(!has)return;dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(1.25*NSEC_PER_SEC)),dispatch_get_main_queue(),^{[RYGDeveloperTopicViewController activatePersistedNativeFeatures];});}}
