#import "RYGRuntimeInventory.h"
#import "RYGRuntimeMachOInspector.h"
#include <stdlib.h>

static NSArray<NSString *> *RYGInventoryBasePaths(void) {
    NSMutableArray *paths=[NSMutableArray array];
    NSString *bundle=NSBundle.mainBundle.bundlePath?:@"";
    if(bundle.length){[paths addObject:[bundle stringByAppendingPathComponent:@"RyukGramRuntime"]];[paths addObject:bundle];}
    [paths addObject:@"/Library/Application Support/RyukGram/runtime"];
    [paths addObject:@"/var/jb/Library/Application Support/RyukGram/runtime"];
    return paths.copy;
}
static NSDictionary *RYGInventoryJSONAtPath(NSString *path){NSData *d=[NSData dataWithContentsOfFile:path];if(!d.length)return @{};id o=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];return [o isKindOfClass:NSDictionary.class]?o:@{};}
static NSDictionary *RYGBuiltInInstagramInventory(void){return @{@"id":@"instagram_current",@"image":@"Instagram",@"uuid":@"4C4C443A-5555-3144-A192-8F033FB73CED",@"source":@"Instagram(2) binary analysis",@"candidates":@[
@{@"kind":@"objc",@"selector":@"isEmployee",@"family":@"internal"},@{@"kind":@"objc",@"selector":@"isEmployeeBuild",@"family":@"internal"},@{@"kind":@"objc",@"selector":@"isIGInternal",@"family":@"internal"},@{@"kind":@"objc",@"selector":@"internalSettingsAvailabilityStatus",@"family":@"internal"},@{@"kind":@"objc",@"selector":@"showInternalSettings",@"family":@"internal"},@{@"kind":@"objc",@"selector":@"showLoggedOutInternalSettings",@"family":@"internal"},@{@"kind":@"objc",@"selector":@"showShakeToReportPreferenceToggle",@"family":@"bug-report"},@{@"kind":@"objc",@"selector":@"showDogfoodingAssistant",@"family":@"dogfood"},@{@"kind":@"objc",@"selector":@"showDebugMenu",@"family":@"debug"},@{@"kind":@"objc",@"selector":@"showDebugMenuWithEntryPoint:",@"family":@"debug"},@{@"kind":@"objc",@"selector":@"isInternalOnly",@"family":@"internal"},@{@"kind":@"objc",@"selector":@"rageShakeDetectorEnabled",@"family":@"bug-report"},@{@"kind":@"objc",@"selector":@"isTrayAttachedToHeaderEnabled:",@"family":@"stories"},@{@"kind":@"objc",@"selector":@"isStoryViewerCardAnimationEnabledWithLauncherSet:",@"family":@"stories"}]};}
static NSDictionary *RYGBuiltInFBSharedInventory(void){return @{@"id":@"fbsharedframework_current",@"image":@"FBSharedFramework",@"uuid":@"4C4C44B7-5555-3144-A167-D73E543FBB32",@"source":@"FBSharedFramework(3) binary analysis",@"candidates":@[
@{@"kind":@"c",@"symbol":@"_EasyGatingGetBoolean_Internal_DoNotUseOrMock",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingPlatformGetBoolean",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingGetInt32_Internal_DoNotUseOrMock",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingPlatformGetInt32",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingGetInt64_Internal_DoNotUseOrMock",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingPlatformGetInt64",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingGetDouble_Internal_DoNotUseOrMock",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingPlatformGetDouble",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingCopyString_Internal_DoNotUseOrMock",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_EasyGatingPlatformCopyString",@"family":@"easygating"},@{@"kind":@"c",@"symbol":@"_IGMobileConfigSetConfigOverrides",@"family":@"mobileconfig"},@{@"kind":@"c",@"symbol":@"_IGMobileConfigForceUpdateConfigs",@"family":@"mobileconfig"},@{@"kind":@"c",@"symbol":@"_IGMobileConfigTryUpdateConfigsWithCompletion",@"family":@"mobileconfig"}]};}
static NSDictionary *RYGBuiltInManifest(void){return @{@"format":@2,@"product":@"Instagram",@"groups":@[@{@"id":@"instagram_current",@"image":@"Instagram",@"uuid":@"4C4C443A-5555-3144-A192-8F033FB73CED",@"candidates_total":@14},@{@"id":@"fbsharedframework_current",@"image":@"FBSharedFramework",@"uuid":@"4C4C44B7-5555-3144-A167-D73E543FBB32",@"candidates_total":@13}]};}

@implementation RYGRuntimeInventory
+ (NSDictionary *)manifest{for(NSString *b in RYGInventoryBasePaths()){NSDictionary *m=RYGInventoryJSONAtPath([b stringByAppendingPathComponent:@"ryg_runtime_inventory_manifest.json"]);if(m.count)return m;}return RYGBuiltInManifest();}
+ (NSDictionary *)inventoryNamed:(NSString *)name{if(!name.length)return @{};NSString *s=[[name lastPathComponent] stringByDeletingPathExtension];for(NSString *b in RYGInventoryBasePaths()){NSDictionary *v=RYGInventoryJSONAtPath([b stringByAppendingPathComponent:[s stringByAppendingPathExtension:@"json"]]);if(v.count)return v;}if([s isEqualToString:@"instagram_current"])return RYGBuiltInInstagramInventory();if([s isEqualToString:@"fbsharedframework_current"])return RYGBuiltInFBSharedInventory();return @{};}
+ (NSArray<NSString *> *)availableInventoryNames{NSMutableArray *n=[NSMutableArray array];for(NSDictionary *g in [self manifest][@"groups"]?:@[]){NSString *gid=[g[@"id"] isKindOfClass:NSString.class]?g[@"id"]:nil;if(gid.length)[n addObject:gid];}return n.copy;}
+ (NSArray<NSDictionary *> *)candidatesForImagePath:(NSString *)imagePath{NSString *last=imagePath.lastPathComponent.lowercaseString?:@"";NSString *uuid=RYGRuntimeMachOImageUUID(imagePath)?:@"";NSMutableArray *out=[NSMutableArray array];for(NSString *name in [self availableInventoryNames]){NSDictionary *inv=[self inventoryNamed:name];NSString *expected=[inv[@"image"] isKindOfClass:NSString.class]?[inv[@"image"] lowercaseString]:@"";NSString *expectedUUID=[inv[@"uuid"] isKindOfClass:NSString.class]?inv[@"uuid"]:@"";BOOL imageMatch=expected.length&&([last isEqualToString:expected]||[last containsString:expected]);BOOL uuidMatch=expectedUUID.length&&uuid.length&&[uuid caseInsensitiveCompare:expectedUUID]==NSOrderedSame;if(!imageMatch&&!uuidMatch)continue;NSArray *c=[inv[@"candidates"] isKindOfClass:NSArray.class]?inv[@"candidates"]:@[];[out addObjectsFromArray:c];}return out.copy;}
+ (NSString *)diagnosticText{NSMutableString *t=[NSMutableString stringWithFormat:@"groups=%lu",(unsigned long)[self availableInventoryNames].count];for(NSString *n in [self availableInventoryNames]){NSDictionary *i=[self inventoryNamed:n];[t appendFormat:@"\n%@ image=%@ uuid=%@ candidates=%lu",n,i[@"image"]?:@"?",i[@"uuid"]?:@"?",(unsigned long)[i[@"candidates"] count]];}return t;}
@end
