#import "SCIDexKitViewController.h"
#import "../Features/ExpFlags/SCIDexKitScanner.h"
#import "../Features/ExpFlags/SCIDexKitStore.h"
#import "../Features/ExpFlags/SCIDexKitBoolRouter.h"

typedef NS_ENUM(NSInteger, SCIDexKitUIFilter) { SCIDexKitUIFilterAll, SCIDexKitUIFilterSeen, SCIDexKitUIFilterOn, SCIDexKitUIFilterOff, SCIDexKitUIFilterForced };

@interface SCIDexKitCell : UITableViewCell
@property UILabel *title; @property UILabel *detail; @property UISwitch *sw; @property UIButton *systemButton;
@property (copy) void (^changed)(BOOL); @property (copy) void (^systemPressed)(void);
@end
@implementation SCIDexKitCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier { self=[super initWithStyle:style reuseIdentifier:reuseIdentifier]; if(!self)return nil; self.backgroundColor=UIColor.secondarySystemGroupedBackgroundColor; self.contentView.backgroundColor=self.backgroundColor; _title=[UILabel new]; _title.font=[UIFont monospacedSystemFontOfSize:13 weight:UIFontWeightRegular]; _title.numberOfLines=2; _title.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_title]; _detail=[UILabel new]; _detail.font=[UIFont systemFontOfSize:11]; _detail.textColor=UIColor.secondaryLabelColor; _detail.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_detail]; _sw=[UISwitch new]; _sw.translatesAutoresizingMaskIntoConstraints=NO; [_sw addTarget:self action:@selector(swChanged) forControlEvents:UIControlEventValueChanged]; [self.contentView addSubview:_sw]; _systemButton=[UIButton buttonWithType:UIButtonTypeSystem]; [_systemButton setTitle:@"System" forState:UIControlStateNormal]; _systemButton.titleLabel.font=[UIFont systemFontOfSize:12 weight:UIFontWeightSemibold]; _systemButton.translatesAutoresizingMaskIntoConstraints=NO; [_systemButton addTarget:self action:@selector(sys) forControlEvents:UIControlEventTouchUpInside]; [self.contentView addSubview:_systemButton]; [NSLayoutConstraint activateConstraints:@[[_sw.centerYAnchor constraintEqualToAnchor:self.contentView.centerYAnchor],[_sw.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:-12],[_systemButton.centerYAnchor constraintEqualToAnchor:_sw.centerYAnchor],[_systemButton.trailingAnchor constraintEqualToAnchor:_sw.leadingAnchor constant:-10],[_title.topAnchor constraintEqualToAnchor:self.contentView.topAnchor constant:9],[_title.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:16],[_title.trailingAnchor constraintEqualToAnchor:_systemButton.leadingAnchor constant:-8],[_detail.topAnchor constraintEqualToAnchor:_title.bottomAnchor constant:3],[_detail.leadingAnchor constraintEqualToAnchor:_title.leadingAnchor],[_detail.trailingAnchor constraintEqualToAnchor:_title.trailingAnchor],[_detail.bottomAnchor constraintEqualToAnchor:self.contentView.bottomAnchor constant:-9]]]; return self; }
- (void)swChanged { if(_changed)_changed(_sw.isOn); } - (void)sys { if(_systemPressed)_systemPressed(); }
@end

@interface SCIDexKitHeader : UITableViewHeaderFooterView
@property UILabel *title; @property UILabel *detail; @property UISwitch *sw; @property UIButton *systemButton;
@property (copy) void (^changed)(BOOL); @property (copy) void (^systemPressed)(void);
@end
@implementation SCIDexKitHeader
- (instancetype)initWithReuseIdentifier:(NSString *)reuseIdentifier { self=[super initWithReuseIdentifier:reuseIdentifier]; if(!self)return nil; self.contentView.backgroundColor=UIColor.systemGroupedBackgroundColor; _title=[UILabel new]; _title.font=[UIFont monospacedSystemFontOfSize:12 weight:UIFontWeightSemibold]; _title.numberOfLines=2; _title.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_title]; _detail=[UILabel new]; _detail.font=[UIFont systemFontOfSize:10]; _detail.textColor=UIColor.secondaryLabelColor; _detail.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_detail]; _sw=[UISwitch new]; _sw.translatesAutoresizingMaskIntoConstraints=NO; [_sw addTarget:self action:@selector(swChanged) forControlEvents:UIControlEventValueChanged]; [self.contentView addSubview:_sw]; _systemButton=[UIButton buttonWithType:UIButtonTypeSystem]; [_systemButton setTitle:@"System" forState:UIControlStateNormal]; _systemButton.titleLabel.font=[UIFont systemFontOfSize:12 weight:UIFontWeightSemibold]; _systemButton.translatesAutoresizingMaskIntoConstraints=NO; [_systemButton addTarget:self action:@selector(sys) forControlEvents:UIControlEventTouchUpInside]; [self.contentView addSubview:_systemButton]; [NSLayoutConstraint activateConstraints:@[[_sw.centerYAnchor constraintEqualToAnchor:self.contentView.centerYAnchor],[_sw.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:-12],[_systemButton.centerYAnchor constraintEqualToAnchor:_sw.centerYAnchor],[_systemButton.trailingAnchor constraintEqualToAnchor:_sw.leadingAnchor constant:-10],[_title.topAnchor constraintEqualToAnchor:self.contentView.topAnchor constant:8],[_title.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:14],[_title.trailingAnchor constraintEqualToAnchor:_systemButton.leadingAnchor constant:-8],[_detail.topAnchor constraintEqualToAnchor:_title.bottomAnchor constant:3],[_detail.leadingAnchor constraintEqualToAnchor:_title.leadingAnchor],[_detail.trailingAnchor constraintEqualToAnchor:_title.trailingAnchor],[_detail.bottomAnchor constraintLessThanOrEqualToAnchor:self.contentView.bottomAnchor constant:-8]]]; return self; }
- (void)swChanged { if(_changed)_changed(_sw.isOn); } - (void)sys { if(_systemPressed)_systemPressed(); }
@end

@interface SCIDexKitViewController () <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate>
@property UISegmentedControl *filter; @property UISearchBar *search; @property UITableView *table; @property UILabel *footer;
@property NSArray<SCIDexKitDescriptor *> *rows; @property NSArray<NSString *> *sections; @property NSDictionary<NSString *,NSArray<SCIDexKitDescriptor *> *> *groups;
@property SCIDexKitScannerMode scanMode; @property NSString *query;
@end

@implementation SCIDexKitViewController
- (void)viewDidLoad { [super viewDidLoad]; self.title=@"SCI DexKit 2.0"; self.view.backgroundColor=UIColor.systemGroupedBackgroundColor; _scanMode=SCIDexKitScannerModeCurated; _filter=[[UISegmentedControl alloc] initWithItems:@[@"All",@"Seen",@"ON",@"OFF",@"Forced"]]; _filter.selectedSegmentIndex=0; [_filter addTarget:self action:@selector(reload) forControlEvents:UIControlEventValueChanged]; _filter.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:_filter]; _search=[UISearchBar new]; _search.searchBarStyle=UISearchBarStyleMinimal; _search.placeholder=@"Search owner/function/source"; _search.delegate=self; _search.autocapitalizationType=UITextAutocapitalizationTypeNone; _search.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:_search]; _footer=[UILabel new]; _footer.font=[UIFont systemFontOfSize:11]; _footer.textColor=UIColor.secondaryLabelColor; _footer.numberOfLines=0; _footer.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:_footer]; _table=[[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStyleInsetGrouped]; _table.dataSource=self; _table.delegate=self; _table.rowHeight=UITableViewAutomaticDimension; _table.estimatedRowHeight=58; _table.backgroundColor=UIColor.systemGroupedBackgroundColor; [_table registerClass:SCIDexKitCell.class forCellReuseIdentifier:@"cell"]; [_table registerClass:SCIDexKitHeader.class forHeaderFooterViewReuseIdentifier:@"header"]; _table.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:_table]; self.navigationItem.rightBarButtonItems=@[[[UIBarButtonItem alloc] initWithTitle:@"Refresh" style:UIBarButtonItemStylePlain target:self action:@selector(reload)], [[UIBarButtonItem alloc] initWithTitle:@"Observe" style:UIBarButtonItemStylePlain target:self action:@selector(observeVisible)]]; UILayoutGuide *g=self.view.safeAreaLayoutGuide; [NSLayoutConstraint activateConstraints:@[[_filter.topAnchor constraintEqualToAnchor:g.topAnchor constant:8],[_filter.leadingAnchor constraintEqualToAnchor:g.leadingAnchor constant:12],[_filter.trailingAnchor constraintEqualToAnchor:g.trailingAnchor constant:-12],[_search.topAnchor constraintEqualToAnchor:_filter.bottomAnchor constant:4],[_search.leadingAnchor constraintEqualToAnchor:g.leadingAnchor constant:8],[_search.trailingAnchor constraintEqualToAnchor:g.trailingAnchor constant:-8],[_footer.topAnchor constraintEqualToAnchor:_search.bottomAnchor constant:2],[_footer.leadingAnchor constraintEqualToAnchor:g.leadingAnchor constant:14],[_footer.trailingAnchor constraintEqualToAnchor:g.trailingAnchor constant:-14],[_table.topAnchor constraintEqualToAnchor:_footer.bottomAnchor constant:4],[_table.leadingAnchor constraintEqualToAnchor:g.leadingAnchor],[_table.trailingAnchor constraintEqualToAnchor:g.trailingAnchor],[_table.bottomAnchor constraintEqualToAnchor:g.bottomAnchor]]]; [self reload]; }
- (void)observeVisible { SCIDexKitEnableSessionObservationForDescriptors(self.rows ?: @[]); [self reload]; dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(1*NSEC_PER_SEC)),dispatch_get_main_queue(),^{[self reload];}); }
- (SCIDexKitKnownBoolState)effective:(SCIDexKitDescriptor *)d { return [SCIDexKitStore effectiveStateForOverrideKey:d.overrideKey observedKey:d.observedKey]; }
- (void)reload { NSArray *all=[SCIDexKitScanner scanDescriptorsWithMode:_scanMode query:_query]; NSMutableArray *filtered=[NSMutableArray array]; for(SCIDexKitDescriptor *d in all){ SCIDexKitKnownBoolState st=[self effective:d]; NSInteger f=_filter.selectedSegmentIndex; if(f==1 && !d.observedKnown)continue; if(f==2 && st!=SCIDexKitKnownBoolStateOn)continue; if(f==3 && st!=SCIDexKitKnownBoolStateOff)continue; if(f==4 && !d.overrideValue)continue; [filtered addObject:d]; } _rows=filtered; NSMutableDictionary *g=[NSMutableDictionary dictionary]; for(SCIDexKitDescriptor *d in _rows){ NSString *k=d.ownerGroupKey; if(!g[k])g[k]=[NSMutableArray array]; [(NSMutableArray *)g[k] addObject:d]; } _sections=[[g allKeys] sortedArrayUsingSelector:@selector(caseInsensitiveCompare:)]; _groups=g; _footer.text=[NSString stringWithFormat:@"Curated %@ · images Instagram+FBSharedFramework · rows=%lu · groups=%lu · hooks=%lu", _scanMode==SCIDexKitScannerModeCurated?@"B-only":@"Raw",(unsigned long)_rows.count,(unsigned long)_sections.count,(unsigned long)SCIDexKitInstalledHookCount()]; [_table reloadData]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return _sections.count; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return [_groups[_sections[section]] count]; }
- (NSArray *)rowsInSection:(NSInteger)section { return _groups[_sections[section]] ?: @[]; }
- (SCIDexKitDescriptor *)desc:(NSIndexPath *)ip { return [self rowsInSection:ip.section][ip.row]; }
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section { SCIDexKitHeader *h=[tableView dequeueReusableHeaderFooterViewWithIdentifier:@"header"]; NSArray *r=[self rowsInSection:section]; SCIDexKitDescriptor *first=r.firstObject; NSUInteger on=0, forced=0, seen=0; for(SCIDexKitDescriptor *d in r){ if([self effective:d]==SCIDexKitKnownBoolStateOn)on++; if(d.overrideValue)forced++; if(d.observedKnown)seen++; } h.title.text=first.ownerDisplayName; h.detail.text=[NSString stringWithFormat:@"%@ · funcs %lu · seen %lu · forced %lu", first.imageBasename,(unsigned long)r.count,(unsigned long)seen,(unsigned long)forced]; [h.sw setOn:(r.count && on==r.count) animated:NO]; h.systemButton.enabled=forced>0; h.systemButton.alpha=forced>0?1:.35; __weak typeof(self) ws=self; h.changed=^(BOOL v){ for(SCIDexKitDescriptor *d in r){ [SCIDexKitStore setOverrideValue:@(v) forKey:d.overrideKey]; SCIDexKitInstallHookForDescriptor(d,SCIDexKitInstallReasonUserOverride,nil);} [ws reload]; }; h.systemPressed=^{ for(SCIDexKitDescriptor *d in r){ [SCIDexKitStore setOverrideValue:nil forKey:d.overrideKey]; } [ws reload]; }; return h; }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)ip { SCIDexKitCell *c=[tableView dequeueReusableCellWithIdentifier:@"cell" forIndexPath:ip]; SCIDexKitDescriptor *d=[self desc:ip]; c.title.text=d.selectorName; NSString *sys=d.observedKnown?(d.observedValue?@"ON":@"OFF"):@"unknown"; NSString *forced=d.overrideValue?(d.overrideValue.boolValue?@"OVERRIDE ON":@"OVERRIDE OFF"):@"SYSTEM"; NSString *eff=[self effective:d]==SCIDexKitKnownBoolStateOn?@"ON":([self effective:d]==SCIDexKitKnownBoolStateOff?@"OFF":@"unknown"); c.detail.text=[NSString stringWithFormat:@"effective %@ · system %@ · %@ · %@",eff,sys,forced,SCIDexKitIsHookInstalled(d.overrideKey)?@"live":@"off"]; [c.sw setOn:([self effective:d]==SCIDexKitKnownBoolStateOn) animated:NO]; c.systemButton.enabled=d.overrideValue!=nil; c.systemButton.alpha=d.overrideValue?1:.35; __weak typeof(self) ws=self; c.changed=^(BOOL v){ [SCIDexKitStore setOverrideValue:@(v) forKey:d.overrideKey]; SCIDexKitInstallHookForDescriptor(d,SCIDexKitInstallReasonUserOverride,nil); [ws reload]; }; c.systemPressed=^{ [SCIDexKitStore setOverrideValue:nil forKey:d.overrideKey]; [ws reload]; }; return c; }
- (void)tableView:(UITableView *)tv didSelectRowAtIndexPath:(NSIndexPath *)ip { [tv deselectRowAtIndexPath:ip animated:YES]; SCIDexKitDescriptor *d=[self desc:ip]; NSString *msg=[NSString stringWithFormat:@"Owner:\n%@\n\nSelector:\n%@\n\nImage: %@\nType: %@\nOverride: %@\nObserved: %@\nHook: %@\n\n%@",d.className,d.selectorName,d.imageBasename,d.typeEncoding,d.overrideValue?d.overrideValue.stringValue:@"System",d.observedKnown?(d.observedValue?@"ON":@"OFF"):@"unknown",SCIDexKitIsHookInstalled(d.overrideKey)?@"installed":@"not installed",d.overrideKey]; UIAlertController *a=[UIAlertController alertControllerWithTitle:d.selectorName message:msg preferredStyle:UIAlertControllerStyleActionSheet]; [a addAction:[UIAlertAction actionWithTitle:@"Force ON" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *x){[SCIDexKitStore setOverrideValue:@YES forKey:d.overrideKey]; SCIDexKitInstallHookForDescriptor(d,SCIDexKitInstallReasonUserOverride,nil); [self reload];}]]; [a addAction:[UIAlertAction actionWithTitle:@"Force OFF" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *x){[SCIDexKitStore setOverrideValue:@NO forKey:d.overrideKey]; SCIDexKitInstallHookForDescriptor(d,SCIDexKitInstallReasonUserOverride,nil); [self reload];}]]; [a addAction:[UIAlertAction actionWithTitle:@"System" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *x){[SCIDexKitStore setOverrideValue:nil forKey:d.overrideKey]; [self reload];}]]; [a addAction:[UIAlertAction actionWithTitle:@"Copy key" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *x){UIPasteboard.generalPasteboard.string=d.overrideKey;}]]; [a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; UITableViewCell *cell=[tv cellForRowAtIndexPath:ip]; if(a.popoverPresentationController){a.popoverPresentationController.sourceView=cell; a.popoverPresentationController.sourceRect=cell.bounds;} [self presentViewController:a animated:YES completion:nil]; }
- (NSArray<NSString *> *)sectionIndexTitlesForTableView:(UITableView *)tableView { return nil; }
- (void)searchBar:(UISearchBar *)searchBar textDidChange:(NSString *)text { _query=text; [self reload]; }
- (void)searchBarSearchButtonClicked:(UISearchBar *)searchBar { [searchBar resignFirstResponder]; }
@end
