#import "RYGFastMobileConfigBrowserViewController.h"
#import "RYGMobileConfig.h"
#import "RYGMobileConfigJSONIO.h"
#import "../../UI/RYGLiquidGlass.h"
#import "../../UI/RYGPopupChrome.h"
#import "../../Utils.h"
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#import <objc/runtime.h>
#include <stdlib.h>
#include <math.h>

static NSString *const kRYGFastMCSeparator = @": : ";
static const void *kRYGFastMCParamKey = &kRYGFastMCParamKey;

typedef NS_ENUM(NSInteger, RYGFastMCScope) { RYGFastMCScopeAll = 0, RYGFastMCScopeOverridden };
typedef NS_ENUM(NSInteger, RYGFastMCValueType) { RYGFastMCValueTypeUnknown = 0, RYGFastMCValueTypeBool, RYGFastMCValueTypeInt, RYGFastMCValueTypeDouble, RYGFastMCValueTypeString };
typedef NS_ENUM(NSInteger, RYGFastMCImportKind) { RYGFastMCImportNone = 0, RYGFastMCImportOverrides, RYGFastMCImportNamesMerge, RYGFastMCImportNamesReplace };

static NSString *RYGFastMCNormalize(NSString *value) {
    if (!value.length) return @"";
    NSString *lower = value.lowercaseString; NSMutableString *out=[NSMutableString stringWithCapacity:lower.length]; BOOL pendingSpace=NO;
    for(NSUInteger i=0;i<lower.length;i++){unichar c=[lower characterAtIndex:i];BOOL alnum=(c>='a'&&c<='z')||(c>='0'&&c<='9');if(alnum){if(pendingSpace&&out.length)[out appendString:@" "];[out appendFormat:@"%C",c];pendingSpace=NO;}else pendingSpace=out.length>0;} return out.copy;
}
static NSArray<NSString *> *RYGFastMCTokens(NSString *query){NSString*n=RYGFastMCNormalize(query);return n.length?[n componentsSeparatedByString:@" "]:@[];}
static BOOL RYGFastMCBlobMatches(NSString *blob,NSArray<NSString*>*tokens){if(!tokens.count)return YES;NSString*text=blob?:@"";NSString*compact=[text stringByReplacingOccurrencesOfString:@" " withString:@""];for(NSString*t in tokens){if([text containsString:t])continue;NSString*ct=[t stringByReplacingOccurrencesOfString:@" " withString:@""];if(![compact containsString:ct])return NO;}return YES;}
static BOOL RYGFastMCParseLine(NSString*line,unsigned int*paramIndex,NSString**valueText){if(![line isKindOfClass:NSString.class])return NO;NSRange sep=[line rangeOfString:kRYGFastMCSeparator];if(sep.location==NSNotFound)return NO;NSString*i=[[line substringToIndex:sep.location]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];const char*r=i.UTF8String;if(!r||!*r||*r=='-')return NO;char*e=NULL;unsigned long long n=strtoull(r,&e,10);if(e==r||*e!='\0'||n>UINT32_MAX)return NO;if(paramIndex)*paramIndex=(unsigned int)n;if(valueText)*valueText=[line substringFromIndex:NSMaxRange(sep)];return YES;}
static NSString *RYGFastMCConfigKey(unsigned int c){return[NSString stringWithFormat:@"%u:",c];}
static NSString *RYGFastMCValueKey(unsigned int c,unsigned int p){return[NSString stringWithFormat:@"%u:%u",c,p];}
static id RYGFastMCParsedRuntimeValue(RYGMCParam*p,NSString*text){if(!p||!text)return nil;NSString*t=[text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];switch(p.type){case RYGMCTypeBool:{NSString*v=t.lowercaseString;if([v isEqualToString:@"true"])return @YES;if([v isEqualToString:@"false"])return @NO;return nil;}case RYGMCTypeInt:{const char*r=t.UTF8String;char*e=NULL;long long v=strtoll(r,&e,10);return r&&*r&&e!=r&&*e=='\0'?@(v):nil;}case RYGMCTypeDouble:{const char*r=t.UTF8String;char*e=NULL;double v=strtod(r,&e);return r&&*r&&e!=r&&*e=='\0'&&isfinite(v)?@(v):nil;}case RYGMCTypeString:return text;default:return nil;}}

@interface RYGFastMCDocumentStore:NSObject
@property(nonatomic,strong)NSMutableDictionary<NSString*,id>*root;@property(nonatomic,strong)NSMutableDictionary<NSString*,NSString*>*values;@property(nonatomic,strong)NSMutableSet<NSNumber*>*overriddenConfigs;
-(void)load;-(NSString*)valueTextForParam:(RYGMCParam*)p;-(BOOL)configIsOverridden:(RYGMCConfig*)c;-(BOOL)setValueText:(NSString*)v forParam:(RYGMCParam*)p error:(NSError**)e;-(NSData*)serialized:(NSError**)e;
@end
@implementation RYGFastMCDocumentStore
-(instancetype)init{if((self=[super init])){_root=[NSMutableDictionary dictionary];_values=[NSMutableDictionary dictionary];_overriddenConfigs=[NSMutableSet set];}return self;}
-(void)reindex{[self.values removeAllObjects];[self.overriddenConfigs removeAllObjects];[self.root enumerateKeysAndObjectsUsingBlock:^(NSString*k,id obj,BOOL*stop){(void)stop;if(![k isKindOfClass:NSString.class]||![obj isKindOfClass:NSArray.class])return;NSString*d=[k hasSuffix:@":"]?[k substringToIndex:k.length-1]:k;const char*r=d.UTF8String;char*e=NULL;unsigned long long cfg=strtoull(r,&e,10);if(!r||e==r||*e!='\0'||cfg>UINT32_MAX)return;BOOL any=NO;for(id raw in(NSArray*)obj){unsigned int idx=0;NSString*v=nil;if(RYGFastMCParseLine(raw,&idx,&v)){self.values[RYGFastMCValueKey((unsigned int)cfg,idx)]=v?:@"";any=YES;}}if(any)[self.overriddenConfigs addObject:@((unsigned int)cfg)];}];}
-(void)load{NSError*e=nil;NSData*d=[RYGMobileConfig.shared ryg_exportOverridesData:&e];id j=d.length?[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:&e]:nil;self.root=[j isKindOfClass:NSDictionary.class]?[(NSDictionary*)j mutableCopy]:[NSMutableDictionary dictionary];[self reindex];}
-(NSString*)valueTextForParam:(RYGMCParam*)p{return p?self.values[RYGFastMCValueKey(p.configNumber,p.paramIndex)]:nil;}
-(BOOL)configIsOverridden:(RYGMCConfig*)c{return c&&[self.overriddenConfigs containsObject:@(c.number)];}
-(NSData*)serialized:(NSError**)e{return[NSJSONSerialization dataWithJSONObject:self.root?:@{} options:0 error:e];}
-(BOOL)setValueText:(NSString*)valueText forParam:(RYGMCParam*)p error:(NSError**)error{if(!p)return NO;NSString*k=RYGFastMCConfigKey(p.configNumber);NSArray*existing=[self.root[k] isKindOfClass:NSArray.class]?self.root[k]:@[];NSMutableArray*lines=[NSMutableArray arrayWithCapacity:existing.count+1];for(id raw in existing){if(![raw isKindOfClass:NSString.class])continue;unsigned int idx=0;if(RYGFastMCParseLine(raw,&idx,NULL)&&idx==p.paramIndex)continue;[lines addObject:raw];}if(valueText)[lines addObject:[NSString stringWithFormat:@"%u%@%@",p.paramIndex,kRYGFastMCSeparator,valueText]];[lines sortUsingComparator:^NSComparisonResult(NSString*a,NSString*b){unsigned int ai=UINT32_MAX,bi=UINT32_MAX;RYGFastMCParseLine(a,&ai,NULL);RYGFastMCParseLine(b,&bi,NULL);return ai==bi?NSOrderedSame:(ai<bi?NSOrderedAscending:NSOrderedDescending);}];if(lines.count)self.root[k]=lines.copy;else[self.root removeObjectForKey:k];RYGMobileConfig*engine=RYGMobileConfig.shared;if(p.isRuntimeBacked&&RYGMCTypeIsRuntimeValue(p.type)){if(valueText){id rv=RYGFastMCParsedRuntimeValue(p,valueText);if(!rv||![engine setOverride:rv for:p]){if(error)*error=[NSError errorWithDomain:@"com.ryukgram.mobileconfig.snapshot" code:1 userInfo:@{NSLocalizedDescriptionKey:@"Native MobileConfig rejected this override."}];return NO;}}else[engine clearOverrideFor:p];}NSData*data=[self serialized:error];if(!data)return NO;NSString*path=[engine ryg_nativeOverridesJSONPath];if(path.length&&![data writeToFile:path options:NSDataWritingAtomic error:error])return NO;[engine ryg_syncPersistedJSONToNativeDataDirectory];[self reindex];return YES;}
@end

static RYGFastMCValueType RYGFastMCTypeForParam(RYGMCParam*p,NSString*doc){if(p.isRuntimeBacked){switch(p.type){case RYGMCTypeBool:return RYGFastMCValueTypeBool;case RYGMCTypeInt:return RYGFastMCValueTypeInt;case RYGMCTypeDouble:return RYGFastMCValueTypeDouble;case RYGMCTypeString:return RYGFastMCValueTypeString;default:break;}}NSString*t=[doc stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet],*l=t.lowercaseString;if([l isEqualToString:@"true"]||[l isEqualToString:@"false"])return RYGFastMCValueTypeBool;if(t.length){const char*r=t.UTF8String;char*e=NULL;(void)strtoll(r,&e,10);if(e!=r&&*e=='\0')return RYGFastMCValueTypeInt;e=NULL;double d=strtod(r,&e);if(e!=r&&*e=='\0'&&isfinite(d))return RYGFastMCValueTypeDouble;return RYGFastMCValueTypeString;}return RYGFastMCValueTypeUnknown;}

@interface RYGFastMCConfigDetailViewController:UITableViewController<UISearchResultsUpdating>
@property(nonatomic,strong)RYGMCConfig*config;@property(nonatomic,strong)RYGFastMCDocumentStore*store;@property(nonatomic,copy)NSArray<RYGMCParam*>*visibleParams;@property(nonatomic,strong)UISearchController*searchController;@property(nonatomic,copy)void(^documentDidChange)(void);@property(nonatomic,strong)NSMutableDictionary<NSNumber*,id>*nativeSnapshot;
@end
@interface RYGFastMobileConfigBrowserViewController()<UISearchResultsUpdating,UIDocumentPickerDelegate>
@property(nonatomic,copy)NSArray<RYGMCConfig*>*allConfigs;@property(nonatomic,copy)NSArray<RYGMCConfig*>*visibleConfigs;@property(nonatomic,copy)NSDictionary<NSNumber*,NSString*>*searchBlobs;@property(nonatomic,strong)RYGFastMCDocumentStore*store;@property(nonatomic,strong)UISearchController*searchController;@property(nonatomic,assign)RYGFastMCScope scope;@property(nonatomic,assign)BOOL loading;@property(nonatomic,assign)NSUInteger generation;@property(nonatomic,assign)RYGFastMCImportKind importKind;
@end

@implementation RYGFastMobileConfigBrowserViewController
-(instancetype)init{return[super initWithStyle:UITableViewStyleInsetGrouped];}
-(void)viewDidLoad{[super viewDidLoad];self.title=@"MobileConfig";self.view.backgroundColor=[RYGPopupChrome backgroundColor];self.tableView.backgroundColor=[RYGPopupChrome backgroundColor];self.tableView.keyboardDismissMode=UIScrollViewKeyboardDismissModeOnDrag;self.tableView.rowHeight=UITableViewAutomaticDimension;self.tableView.estimatedRowHeight=56;self.searchController=[UISearchController new];self.searchController.searchResultsUpdater=self;self.searchController.obscuresBackgroundDuringPresentation=NO;self.searchController.searchBar.placeholder=@"Config, parameter or ID — spaces/underscores both work";self.navigationItem.searchController=self.searchController;self.navigationItem.hidesSearchBarWhenScrolling=NO;self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithImage:[UIImage systemImageNamed:@"ellipsis.circle"] menu:[self actionsMenu]];RYGLiquidGlassApplyToViewController(self);dispatch_async(dispatch_get_main_queue(),^{[self loadSnapshot:NO];});}
-(UIMenu*)actionsMenu{__weak typeof(self)w=self;UIAction*apply=[UIAction actionWithTitle:@"Apply overrides" image:[UIImage systemImageNamed:@"checkmark.circle"] identifier:nil handler:^(__unused UIAction*a){[RYGMobileConfig.shared reapplyOverridesToNativeTable];[RYGMobileConfig.shared ryg_syncPersistedJSONToNativeDataDirectory];}];UIAction*imp=[UIAction actionWithTitle:@"Import mc_overrides.json" image:[UIImage systemImageNamed:@"square.and.arrow.down"] identifier:nil handler:^(__unused UIAction*a){[w beginImport:RYGFastMCImportOverrides];}];UIAction*exp=[UIAction actionWithTitle:@"Export mc_overrides.json" image:[UIImage systemImageNamed:@"square.and.arrow.up"] identifier:nil handler:^(__unused UIAction*a){[w exportOverrides];}];UIAction*merge=[UIAction actionWithTitle:@"Update IDs / names (merge)" image:[UIImage systemImageNamed:@"arrow.triangle.merge"] identifier:nil handler:^(__unused UIAction*a){[w beginImport:RYGFastMCImportNamesMerge];}];UIAction*replace=[UIAction actionWithTitle:@"Replace IDs / names" image:[UIImage systemImageNamed:@"arrow.clockwise"] identifier:nil handler:^(__unused UIAction*a){[w beginImport:RYGFastMCImportNamesReplace];}];UIAction*exportNames=[UIAction actionWithTitle:@"Export id_name_mapping.json" image:[UIImage systemImageNamed:@"doc.badge.arrow.up"] identifier:nil handler:^(__unused UIAction*a){[w exportNames];}];UIAction*refresh=[UIAction actionWithTitle:@"Refresh runtime snapshot" image:[UIImage systemImageNamed:@"arrow.clockwise.circle"] identifier:nil handler:^(__unused UIAction*a){[w loadSnapshot:YES];}];return[UIMenu menuWithTitle:@"MobileConfig" children:@[apply,imp,exp,merge,replace,exportNames,refresh]];}
-(void)beginImport:(RYGFastMCImportKind)kind{self.importKind=kind;UIDocumentPickerViewController*p=[[UIDocumentPickerViewController alloc]initForOpeningContentTypes:@[UTTypeJSON] asCopy:YES];p.delegate=self;[self presentViewController:p animated:YES completion:nil];}
-(void)exportData:(NSData*)data name:(NSString*)name{if(!data.length)return;NSURL*u=[NSURL fileURLWithPath:[NSTemporaryDirectory() stringByAppendingPathComponent:name]];[data writeToURL:u atomically:YES];UIDocumentPickerViewController*p=[[UIDocumentPickerViewController alloc]initForExportingURLs:@[u] asCopy:YES];[self presentViewController:p animated:YES completion:nil];}
-(void)exportOverrides{NSError*e=nil;NSData*d=[RYGMobileConfig.shared ryg_exportOverridesData:&e];if(d.length)[self exportData:d name:@"mc_overrides.json"];else[RYGUtils showErrorHUDWithDescription:e.localizedDescription?:@"No overrides to export."];}
-(void)exportNames{NSError*e=nil;NSData*d=[RYGMobileConfig.shared ryg_exportNameMappingData:&e];if(d.length)[self exportData:d name:@"id_name_mapping.json"];else[RYGUtils showErrorHUDWithDescription:e.localizedDescription?:@"No mapping to export."];}
-(void)documentPicker:(UIDocumentPickerViewController*)controller didPickDocumentsAtURLs:(NSArray<NSURL*>*)urls{(void)controller;NSURL*u=urls.firstObject;NSData*d=u?[NSData dataWithContentsOfURL:u]:nil;if(!d.length)return;NSError*e=nil;BOOL ok=NO;if(self.importKind==RYGFastMCImportOverrides){NSUInteger applied=0;ok=[RYGMobileConfig.shared ryg_importAndApplyOverridesData:d appliedCount:&applied error:&e];if(ok)[RYGMobileConfig.shared ryg_syncPersistedJSONToNativeDataDirectory];}else{RYGMCNameMappingImportMode mode=self.importKind==RYGFastMCImportNamesReplace?RYGMCNameMappingImportModeReplace:RYGMCNameMappingImportModeMerge;ok=[RYGMobileConfig.shared ryg_importNameMappingData:d mode:mode error:&e];}self.importKind=RYGFastMCImportNone;if(!ok){[RYGUtils showErrorHUDWithDescription:e.localizedDescription?:@"Import failed."];return;}[self loadSnapshot:YES];}
-(void)loadSnapshot:(BOOL)refresh{if(self.loading)return;self.loading=YES;NSUInteger gen=++self.generation;UIActivityIndicatorView*s=[[UIActivityIndicatorView alloc]initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium];[s startAnimating];self.tableView.backgroundView=s;__weak typeof(self)w=self;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{RYGMobileConfig*engine=RYGMobileConfig.shared;if(refresh)[engine reloadFromRuntime];else[engine prepare];NSArray*configs=engine.allConfigs?:@[];RYGFastMCDocumentStore*store=[RYGFastMCDocumentStore new];[store load];NSMutableDictionary*blobs=[NSMutableDictionary dictionaryWithCapacity:configs.count];for(RYGMCConfig*cfg in configs){@autoreleasepool{NSMutableString*str=[NSMutableString stringWithFormat:@"%@ %u ",RYGFastMCNormalize(cfg.name),cfg.number];for(RYGMCParam*p in cfg.params)[str appendFormat:@"%@ %u %llu ",RYGFastMCNormalize(p.name),p.paramIndex,p.paramID];blobs[@(cfg.number)]=str.copy;}}dispatch_async(dispatch_get_main_queue(),^{__strong typeof(w)self=w;if(!self||gen!=self.generation)return;self.allConfigs=configs;self.searchBlobs=blobs.copy;self.store=store;self.loading=NO;[self applyFilter];});});}
-(void)updateSearchResultsForSearchController:(UISearchController*)searchController{(void)searchController;[self applyFilter];}
-(void)applyFilter{if(self.loading)return;NSArray*tokens=RYGFastMCTokens(self.searchController.searchBar.text?:@"");NSMutableArray*out=[NSMutableArray array];for(RYGMCConfig*cfg in self.allConfigs?:@[]){if(self.scope==RYGFastMCScopeOverridden&&![self.store configIsOverridden:cfg])continue;if(RYGFastMCBlobMatches(self.searchBlobs[@(cfg.number)],tokens))[out addObject:cfg];}self.visibleConfigs=out.copy;self.tableView.backgroundView=nil;[self.tableView reloadData];}
-(NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section{(void)tableView;(void)section;return self.visibleConfigs.count;}
-(UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)indexPath{UITableViewCell*cell=[tableView dequeueReusableCellWithIdentifier:@"RYGFastMCConfig"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"RYGFastMCConfig"];RYGMCConfig*cfg=self.visibleConfigs[indexPath.row];cell.textLabel.text=cfg.displayName;cell.detailTextLabel.text=[NSString stringWithFormat:@"#%u · %lu params%@",cfg.number,(unsigned long)cfg.params.count,[self.store configIsOverridden:cfg]?@" · overridden":@""];cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;return cell;}
-(void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)indexPath{[tableView deselectRowAtIndexPath:indexPath animated:YES];RYGFastMCConfigDetailViewController*d=[[RYGFastMCConfigDetailViewController alloc]initWithStyle:UITableViewStyleInsetGrouped];d.config=self.visibleConfigs[indexPath.row];d.store=self.store;__weak typeof(self)w=self;d.documentDidChange=^{[w applyFilter];};[self.navigationController pushViewController:d animated:YES];}
@end

@implementation RYGFastMCConfigDetailViewController
-(void)viewDidLoad{[super viewDidLoad];self.title=self.config.name.length?self.config.name:[NSString stringWithFormat:@"Config %u",self.config.number];self.navigationItem.titleView=RYGLiquidGlassNavigationTitleView(self.title);self.view.backgroundColor=[RYGPopupChrome backgroundColor];self.tableView.backgroundColor=[RYGPopupChrome backgroundColor];self.tableView.rowHeight=UITableViewAutomaticDimension;self.tableView.estimatedRowHeight=56;self.visibleParams=self.config.params?:@[];self.nativeSnapshot=[NSMutableDictionary dictionary];self.searchController=[UISearchController new];self.searchController.searchResultsUpdater=self;self.searchController.obscuresBackgroundDuringPresentation=NO;self.searchController.searchBar.placeholder=@"Parameter or ID";self.navigationItem.searchController=self.searchController;self.navigationItem.hidesSearchBarWhenScrolling=NO;RYGLiquidGlassApplyToViewController(self);[self buildNativeSnapshot];}
-(void)buildNativeSnapshot{NSArray*params=self.config.params.copy;__weak typeof(self)w=self;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSMutableDictionary*v=[NSMutableDictionary dictionary];RYGMobileConfig*engine=RYGMobileConfig.shared;for(RYGMCParam*p in params){if(!p.isRuntimeBacked)continue;id x=[engine liveValueFor:p];if(x)v[@(p.paramIndex)]=x;}dispatch_async(dispatch_get_main_queue(),^{w.nativeSnapshot=v;[w.tableView reloadData];});});}
-(void)updateSearchResultsForSearchController:(UISearchController*)sc{NSArray*tokens=RYGFastMCTokens(sc.searchBar.text?:@"");if(!tokens.count)self.visibleParams=self.config.params?:@[];else self.visibleParams=[self.config.params filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(RYGMCParam*p,NSDictionary*b){(void)b;return RYGFastMCBlobMatches([NSString stringWithFormat:@"%@ %u %llu",RYGFastMCNormalize(p.name),p.paramIndex,p.paramID],tokens);}]];[self.tableView reloadData];}
-(NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section{(void)tableView;(void)section;return self.visibleParams.count;}
-(BOOL)setText:(NSString*)text forParam:(RYGMCParam*)p{NSError*e=nil;BOOL ok=[self.store setValueText:text forParam:p error:&e];if(!ok)[RYGUtils showErrorHUDWithDescription:e.localizedDescription?:@"Could not update mc_overrides.json"];else{if(self.documentDidChange)self.documentDidChange();[self.tableView reloadData];}return ok;}
-(void)boolChanged:(UISwitch*)toggle{RYGMCParam*p=objc_getAssociatedObject(toggle,kRYGFastMCParamKey);if(!p)return;BOOL requested=toggle.isOn;if(![self setText:requested?@"true":@"false" forParam:p])toggle.on=!requested;}
-(UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)indexPath{UITableViewCell*cell=[tableView dequeueReusableCellWithIdentifier:@"RYGFastMCParam"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"RYGFastMCParam"];cell.accessoryView=nil;cell.accessoryType=UITableViewCellAccessoryNone;RYGMCParam*p=self.visibleParams[indexPath.row];NSString*override=[self.store valueTextForParam:p];RYGFastMCValueType type=RYGFastMCTypeForParam(p,override);cell.textLabel.text=p.name.length?p.name:[NSString stringWithFormat:@"Parameter %u",p.paramIndex];id native=self.nativeSnapshot[@(p.paramIndex)];NSString*state=override.length?[NSString stringWithFormat:@"override %@",override]:(native?[NSString stringWithFormat:@"native %@",native]:@"native");cell.detailTextLabel.text=[NSString stringWithFormat:@"#%u · %@ · %@",p.paramIndex,p.typeName?:@"mapping",state];if(type==RYGFastMCValueTypeBool){UISwitch*t=[UISwitch new];t.on=override.length?[override.lowercaseString isEqualToString:@"true"]:([native isKindOfClass:NSNumber.class]?[native boolValue]:NO);objc_setAssociatedObject(t,kRYGFastMCParamKey,p,OBJC_ASSOCIATION_RETAIN_NONATOMIC);[t addTarget:self action:@selector(boolChanged:) forControlEvents:UIControlEventValueChanged];cell.accessoryView=t;cell.selectionStyle=UITableViewCellSelectionStyleNone;}else{cell.accessoryType=UITableViewCellAccessoryDisclosureIndicator;cell.selectionStyle=UITableViewCellSelectionStyleDefault;}return cell;}
-(void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)indexPath{UITableViewCell*cell=[tableView cellForRowAtIndexPath:indexPath];[tableView deselectRowAtIndexPath:indexPath animated:YES];RYGMCParam*p=self.visibleParams[indexPath.row];NSString*text=[self.store valueTextForParam:p];RYGFastMCValueType type=RYGFastMCTypeForParam(p,text);if(type==RYGFastMCValueTypeBool)return;UIAlertController*a=[UIAlertController alertControllerWithTitle:p.name.length?p.name:@"MobileConfig value" message:nil preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField*f){f.text=text?:@"";f.keyboardType=(type==RYGFastMCValueTypeInt||type==RYGFastMCValueTypeDouble)?UIKeyboardTypeNumbersAndPunctuation:UIKeyboardTypeDefault;}];[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];if(text.length)[a addAction:[UIAlertAction actionWithTitle:@"Use native / remove" style:UIAlertActionStyleDestructive handler:^(__unused UIAlertAction*x){[self setText:nil forParam:p];}]];[a addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){[self setText:a.textFields.firstObject.text?:@"" forParam:p];}]];if(UIDevice.currentDevice.userInterfaceIdiom==UIUserInterfaceIdiomPad){a.popoverPresentationController.sourceView=cell;a.popoverPresentationController.sourceRect=cell.bounds;}[self presentViewController:a animated:YES completion:nil];}
@end
