#import "RYGMobileConfigJSONIO.h"
#import "RYGMobileConfigNameMappingStore.h"
#import <math.h>
#include <stdlib.h>

static NSString *const kRYGMobileConfigNamesDidChangeNotification = @"RYGMobileConfigNamesDidChange";
@interface RYGMobileConfig (RYGPrivateNativePath)
- (NSString *)mcDirectory;
@end
static NSError *RYGMCJSONError(NSString *message) { return [NSError errorWithDomain:@"com.ryukgram.mobileconfig.json" code:1 userInfo:@{NSLocalizedDescriptionKey:message ?: @"MobileConfig JSON error"}]; }
static NSString *RYGMCJSONValueString(id value, RYGMCType type) { if (type == RYGMCTypeBool) return [value boolValue] ? @"true" : @"false"; if (type == RYGMCTypeInt) return [NSString stringWithFormat:@"%lld", [value longLongValue]]; if (type == RYGMCTypeDouble) return [NSString stringWithFormat:@"%.17g", [value doubleValue]]; return [value isKindOfClass:NSString.class] ? value : [value description]; }
static id RYGMCParseJSONValue(NSString *text, RYGMCType type) { NSString *trim = [text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]; if (type == RYGMCTypeBool) { NSString *lower = trim.lowercaseString; if ([lower isEqualToString:@"true"] || [lower isEqualToString:@"1"] || [lower isEqualToString:@"yes"]) return @YES; if ([lower isEqualToString:@"false"] || [lower isEqualToString:@"0"] || [lower isEqualToString:@"no"]) return @NO; return nil; } if (type == RYGMCTypeInt) { const char *raw = trim.UTF8String; if (!raw || !*raw) return nil; char *end = NULL; long long value = strtoll(raw, &end, 10); return (end != raw && *end == '\0') ? @(value) : nil; } if (type == RYGMCTypeDouble) { const char *raw = trim.UTF8String; if (!raw || !*raw) return nil; char *end = NULL; double value = strtod(raw, &end); return (end != raw && *end == '\0' && isfinite(value)) ? @(value) : nil; } if (type == RYGMCTypeString) return text ?: @""; return nil; }
static NSDictionary<NSNumber *, NSDictionary *> *RYGMCCatalogFromCurrentModels(RYGMobileConfig *mobileConfig) { NSMutableDictionary<NSNumber *, NSDictionary *> *catalog = [NSMutableDictionary dictionary]; for (RYGMCConfig *config in mobileConfig.allConfigs) { NSMutableDictionary<NSNumber *, NSString *> *params = [NSMutableDictionary dictionary]; for (RYGMCParam *param in config.params) if (param.name.length) params[@(param.paramIndex)] = param.name; if (config.name.length || params.count) catalog[@(config.number)] = @{@"name":config.name ?: @"", @"params":params.copy}; } return catalog.copy; }
static BOOL RYGMCVerifyPersistedCatalog(NSDictionary<NSNumber *, NSDictionary *> *expected, NSError **error) { NSDictionary<NSNumber *, NSDictionary *> *actual = RYGMCLoadCachedNameMappingCatalog(error); if (!actual) return NO; for (NSNumber *configNumber in expected) { NSDictionary *wanted = expected[configNumber], *got = actual[configNumber]; if (!got) { if (error) *error = RYGMCJSONError([NSString stringWithFormat:@"Config %@ was not persisted.", configNumber]); return NO; } NSString *wantedName = [wanted[@"name"] isKindOfClass:NSString.class] ? wanted[@"name"] : @""; NSString *gotName = [got[@"name"] isKindOfClass:NSString.class] ? got[@"name"] : @""; if (wantedName.length && ![wantedName isEqualToString:gotName]) { if (error) *error = RYGMCJSONError([NSString stringWithFormat:@"Config %@ name did not round-trip.", configNumber]); return NO; } NSDictionary *wantedParams = [wanted[@"params"] isKindOfClass:NSDictionary.class] ? wanted[@"params"] : @{}; NSDictionary *gotParams = [got[@"params"] isKindOfClass:NSDictionary.class] ? got[@"params"] : @{}; for (NSNumber *paramIndex in wantedParams) if (![wantedParams[paramIndex] isEqual:gotParams[paramIndex]]) { if (error) *error = RYGMCJSONError([NSString stringWithFormat:@"Param %@:%@ did not round-trip.", configNumber, paramIndex]); return NO; } } return YES; }
static void RYGMCPostNamesChanged(RYGMobileConfig *mobileConfig) { void (^post)(void) = ^{ [NSNotificationCenter.defaultCenter postNotificationName:kRYGMobileConfigNamesDidChangeNotification object:mobileConfig]; }; if (NSThread.isMainThread) post(); else dispatch_async(dispatch_get_main_queue(), post); }

@implementation RYGMobileConfig (RYGJSONIO)
- (NSString *)ryg_nativeDataDirectory { NSString *path = nil; @try { path = [self mcDirectory]; } @catch (__unused NSException *exception) {} if (![path isKindOfClass:NSString.class] || !path.length) return nil; BOOL isDirectory = NO; if (![NSFileManager.defaultManager fileExistsAtPath:path isDirectory:&isDirectory] || !isDirectory) return nil; if (![path.pathExtension.lowercaseString isEqualToString:@"data"]) return nil; return path; }
- (NSString *)ryg_nativeNameMappingPath { NSString *directory = [self ryg_nativeDataDirectory]; return directory.length ? [directory stringByAppendingPathComponent:@"id_name_mapping.json"] : nil; }
- (NSString *)ryg_nativeOverridesJSONPath { NSString *directory = [self ryg_nativeDataDirectory]; return directory.length ? [directory stringByAppendingPathComponent:@"mc_overrides.json"] : nil; }
- (BOOL)ryg_importNameMappingData:(NSData *)data error:(NSError **)error { return [self ryg_importNameMappingData:data mode:RYGMCNameMappingImportModeReplace error:error]; }
- (BOOL)ryg_importNameMappingData:(NSData *)data mode:(RYGMCNameMappingImportMode)mode error:(NSError **)error { NSDictionary<NSNumber *, NSDictionary *> *incoming = RYGMCNameMappingCatalogFromData(data, error); if (!incoming) return NO; NSMutableDictionary<NSNumber *, NSDictionary *> *result = [NSMutableDictionary dictionary]; if (mode == RYGMCNameMappingImportModeMerge) { NSDictionary *existing = RYGMCLoadCachedNameMappingCatalog(NULL); if (!existing.count) existing = RYGMCCatalogFromCurrentModels(self); if (existing.count) [result addEntriesFromDictionary:existing]; } RYGMCMergeNameMappingCatalog(result, incoming); if (!RYGMCSaveNameMappingCatalog(result, error)) return NO; if (!RYGMCVerifyPersistedCatalog(result, error)) return NO; NSData *canonical = RYGMCLoadCachedNameMappingData(); NSString *nativePath = [self ryg_nativeNameMappingPath]; if (nativePath.length && canonical.length && ![canonical writeToFile:nativePath options:NSDataWritingAtomic error:error]) return NO; [self reloadFromRuntime]; RYGMCPostNamesChanged(self); return YES; }
- (NSData *)ryg_exportNameMappingData:(NSError **)error { NSData *cached = RYGMCLoadCachedNameMappingData(); if (cached.length) return cached; NSString *nativePath = [self ryg_nativeNameMappingPath]; NSData *native = nativePath.length ? [NSData dataWithContentsOfFile:nativePath options:0 error:nil] : nil; if (native.length) return native; NSDictionary *catalog = RYGMCCatalogFromCurrentModels(self); if (!catalog.count) { if (error) *error = RYGMCJSONError(@"No MobileConfig name mapping is available to export."); return nil; } return RYGMCNameMappingDataFromCatalog(catalog, error); }
- (BOOL)ryg_importAndApplyOverridesData:(NSData *)data appliedCount:(NSUInteger *)appliedCount error:(NSError **)error { if (appliedCount) *appliedCount = 0; if (!data.length) { if (error) *error = RYGMCJSONError(@"The mc_overrides.json file is empty."); return NO; } id json = [NSJSONSerialization JSONObjectWithData:data options:0 error:error]; if (![json isKindOfClass:NSDictionary.class]) { if (error && !*error) *error = RYGMCJSONError(@"mc_overrides.json must be an object keyed by <config>:. "); return NO; } [self prepare]; NSMutableDictionary<NSNumber *, RYGMCConfig *> *configs = [NSMutableDictionary dictionary]; for (RYGMCConfig *config in self.allConfigs) configs[@(config.number)] = config; NSUInteger applied = 0; for (id rawKey in (NSDictionary *)json) { if (![rawKey isKindOfClass:NSString.class]) continue; NSString *configKey = [(NSString *)rawKey stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]; if ([configKey hasSuffix:@":"]) configKey = [configKey substringToIndex:configKey.length - 1]; char *configEnd = NULL; unsigned long long configNumber = strtoull(configKey.UTF8String, &configEnd, 10); if (!configKey.length || configEnd == configKey.UTF8String || *configEnd != '\0') continue; RYGMCConfig *config = configs[@(configNumber)]; id lines = ((NSDictionary *)json)[rawKey]; if (![lines isKindOfClass:NSArray.class] || !config) continue; NSMutableDictionary<NSNumber *, RYGMCParam *> *params = [NSMutableDictionary dictionary]; for (RYGMCParam *param in config.params) params[@(param.paramIndex)] = param; for (id rawLine in (NSArray *)lines) { if (![rawLine isKindOfClass:NSString.class]) continue; NSString *line = rawLine; NSRange separator = [line rangeOfString:@": : "]; if (separator.location == NSNotFound) separator = [line rangeOfString:@"::"]; if (separator.location == NSNotFound) continue; NSString *indexText = [[line substringToIndex:separator.location] stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceCharacterSet]; char *indexEnd = NULL; unsigned long long index = strtoull(indexText.UTF8String, &indexEnd, 10); if (!indexText.length || indexEnd == indexText.UTF8String || *indexEnd != '\0') continue; RYGMCParam *param = params[@(index)]; if (!param || !param.isRuntimeBacked || param.type == RYGMCTypeUnknown) continue; id value = RYGMCParseJSONValue([line substringFromIndex:NSMaxRange(separator)], param.type); if (value && [self setOverride:value for:param]) applied++; } } [self reapplyOverridesToNativeTable]; NSData *canonical = [NSJSONSerialization dataWithJSONObject:json options:0 error:error]; if (!canonical) return NO; NSString *nativePath = [self ryg_nativeOverridesJSONPath]; if (nativePath.length && ![canonical writeToFile:nativePath options:NSDataWritingAtomic error:error]) return NO; if (appliedCount) *appliedCount = applied; return YES; }
- (NSData *)ryg_exportOverridesData:(NSError **)error { NSMutableDictionary<NSString *, NSMutableArray<NSString *> *> *root = [NSMutableDictionary dictionary]; for (RYGMCConfig *config in self.allConfigs) { NSMutableArray<NSString *> *lines = [NSMutableArray array]; for (RYGMCParam *param in config.params) if (param.isRuntimeBacked && param.type != RYGMCTypeUnknown && [self overrideStateFor:param] == RYGMCOverrideSet) { id value = [self overrideValueFor:param]; if (value) [lines addObject:[NSString stringWithFormat:@"%u: : %@", param.paramIndex, RYGMCJSONValueString(value, param.type)]]; } if (lines.count) root[[NSString stringWithFormat:@"%u:", config.number]] = lines; } return [NSJSONSerialization dataWithJSONObject:root options:0 error:error]; }
@end
