name: PR assignment

on:
    pull_request:
        types: [opened, reopened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
            pull-requests: write
        steps:
            - name: 'Auto-assign PR'
              uses: actions/github-script@v9
              with:
                  script: |
                      const { owner, repo } = context.repo;
                      const issue_number = context.payload.pull_request.number;
                      await github.rest.issues.addAssignees({
                          owner,
                          repo,
                          issue_number,
                          assignees: ['faroukbmiled'],
                      });
